### ISSUE TITLE
TravisのTODOリスト

### ISSUE THREAD

**Issue by RyodoTanaka** [CIR-KIT-Unit03/cirkit_unit03_apps#15]
### 依存先のパッケージでTravisが通ってない
- [x] [human_detector](https://github.com/CIR-KIT/human_detector)
- [x] [timed_roslaunch](https://github.com/MoriKen254/timed_roslaunch)

以上が原因で本リポジトリもTravisが通っていない。

### これから先依存するであろうパッケージのTravis
- [x] [waypoint_manager](https://github.com/CIR-KIT/waypoint_manager)
- [x] [remote_monitor](https://github.com/CIR-KIT/remote_monitor)

上記パッケージは以前Travisを通したが現在はパッケージ構成が変わったので、修正する必要がある。

**Comment by MoriKen254** [comment]
@RyodoTanaka 

残件について，解決案はありますか？

https://github.com/CIR-KIT-Unit03/cirkit_unit03_pkgs/issues/2 と合わせてやっつけたいですね♪

**Comment by MoriKen254** [comment]
https://github.com/CIR-KIT/human_detector/pull/4 が承認され，更に`master`にマージされれば，少し状況は改善するかと思います．

後半二件についても追って対応します．

**Comment by MoriKen254** [comment]
一通り通っていると思います。クローズ！
