### ISSUE TITLE
Compilation terminated error

### ISSUE THREAD

**Issue by Ayushas2427** [CIR-KIT-Unit03/cirkit_unit03_apps#18]
On following the "https://github.com/CIR-KIT-Unit03/cirkit_unit03_apps". I am getting the following error.
![error_new](https://cloud.githubusercontent.com/assets/25845090/26752382/230280f8-486c-11e7-8c1b-6b4e2a4b9358.png)
I have tried both the "command line & "script method".
Kindly help in this regard.
Thank you

**Comment by RyodoTanaka** [comment]
@Ayushas2427 
Did you install PCL ?
If did not, please install the pcl like following 
```bash
sudo add-apt-repository ppa:v-launchpad-jochen-sprickerhof-de/pcl
sudo apt-get update
sudo apt-get install -yV libpcl-all
```

best regards.

**Comment by Ayushas2427** [comment]
Sorry for the late reply @RyodoTanaka .
After installing PCL, my system is still showing the same error.
Kindly reply

Note:
This is my output with the command "`sudo add-apt-repository ppa:v-launchpad-jochen-sprickerhof-de/pcl`"

![error_new](https://cloud.githubusercontent.com/assets/25845090/26793527/e548af2c-4a3b-11e7-81aa-fbb2e08e15d2.png)

With the command : "`sudo apt-get update`"
I get a warning sort of in the end as follows:

![error_new](https://cloud.githubusercontent.com/assets/25845090/26793615/424e0f82-4a3c-11e7-9809-17fba4cd139a.png)

And finally, with the final command: "`sudo apt-get install -yV libpcl-all`"
My system shows that "libpcl-all is already the newest version", as i have tried this several times!

Regards

**Comment by Ayushas2427** [comment]
Update: I have removed the Warning of public key.
But still the error exists.

Kindly help!
Regards

**Comment by Ayushas2427** [comment]
Sir. after installing pcl 1.8 and doing all sort of brainstorming, i am getting the following error!

![error_1](https://user-images.githubusercontent.com/25845090/27281739-b08f6332-550a-11e7-884d-03a641adbbef.png)

Kindly revert and help in resolving the issue!
I have been trying each possible way but has failed so far!
Regards

**Comment by AriYu** [comment]
@Ayushas2427
Did you try to remove build and devel directory and run catkin_make after you installed PCL libraries ?

**Comment by Ayushas2427** [comment]
I beg your pardon respected @AriYu , 
but I am not sure how to remove build and devel directory.

Update:
I am editing my comment as something different has been received from the package now!

On running the launch file, the i am having the output as follows:

1: The Rviz and the gazebo are showing the outputs as follows:
![output_1](https://user-images.githubusercontent.com/25845090/27283837-cec8bbce-5513-11e7-8870-340867520e01.png)

2: The terminal is showing the error as follows:
![roa_eror_4](https://user-images.githubusercontent.com/25845090/27283844-dca8432c-5513-11e7-82b7-9b5b53aba778.png)
![ros_error_5](https://user-images.githubusercontent.com/25845090/27283843-dca68c30-5513-11e7-813f-4d219d251f21.png)

It shows that the system is not responding well enough and the local planner is very unstable.
On simulating, the system is responding in a very awkward and unstable manner, especially near obstacles!

Kindly help me with the changes i need to rectify the final issues.

Warm Regards

**Comment by MoriKen254** [comment]
@Ayushas2427 
Thank you very much for your enthusiastic trial to use our package and excuse us to bother you for setting up...

> I beg your pardon respected @AriYu ,
> but I am not sure how to remove build and devel directory.

@AriYu probably meant "try typing the following commands" to completely clean up your environment.

```bash
cd <catkin_ws>
rm -r build devel
```

and then rebuild the workspace with `catkin_make`.

Now, I'm glad that you somehow solved this stuff.

## About your update
Lack of "jsk_visualization"seems to cause the error on the first terminal figure. Try to install as follows.

```bash
sudo apt-get -y install ros-<your ROS distribution>-jsk-visualization
```

>It shows that the system is not responding well enough and the local planner is very unstable.
On simulating, the system is responding in a very awkward and unstable manner, especially near obstacles!

Ummm... Unfortunately, at least I haven't seen such an error. I'm not pretty sure about the error for now but will try to drop a couple of my opinions.

Updating local costmap seems to take a time according to your comment `"a very awkward and unstable manner, especially near obstacles!"`. Chances are adjusting costmap or local planner frequency (or related parameters) to be slower (or make process to run faster) would make the situation better (see [gazebo/local_costmap_params.yaml](https://github.com/CIR-KIT-Unit03/cirkit_unit03_navigation/blob/indigo-devel/cirkit_unit03_move_base/config/gazebo/local_costmap_params.yaml) or [gazebo/base_local_planner_params.yaml](https://github.com/CIR-KIT-Unit03/cirkit_unit03_navigation/blob/indigo-devel/cirkit_unit03_move_base/config/gazebo/base_local_planner_params.yaml)). 

Using a couple of LRFs and handling costmap of them at the same time on gazebo takes some CPU resources (we use Core i5 or i7 usually) so chances are another PC manages the problem. It might be worth a try to use the package on another PC if it's possible.

Sorry for any inconvenience this may have caused you.

Best Regards.

**Comment by MoriKen254** [comment]
Found a related issue on a forum.
http://answers.ros.org/question/164911/move_base-and-extrapolation-errors-into-the-future/

Hope it'll help you.

**Comment by Ayushas2427** [comment]
Respected @MoriKen254 ,
First of all, with all respect, I thank you for such an explanatory response.
Its very encouraging for students like me!
Tomorrw morning (current local time 9:40 IST), after going to the lab, i will check and follow each of your suggestions. Kindly wait till that time for me to revert on this.

Also, I have just seen the use of openCV in cmake files, do you think the lack of the openCV could be the error for this?

Best Regards

**Comment by Ayushas2427** [comment]
Respected,
After searching for the error I am receiving, I think I need to provide some delay value to the tf function.
As per the related solutions,
 i could try the following:
```
listener = tf.TransformListener()
# Give tf some time to fill its buffer
rospy.sleep(2)
listener.waitForTransform("/goal_in_picture","/map",rospy.Time.now(),rospy.Duration(5.0))
```
or

```
time = ros::Time::now();  // or better msg->header.stamp, if available; never ros::Time(0)
success = false;
while (!success) {
  try {
    listener.waitForTransform(target_frame, source_frame, time, ros::Duration(3.0));
    listener.lookupTransform(target_frame, source_frame, time, st);
    success = true;
  } catch (tf::ExtrapolationException e) {
  }
  sleep(0.1);
}
```

or something related.

I frankly do not have the idea of how to deal with "tf". so can you let me know , in which node file or so one needs to make these changes?

Best Regards

**Comment by AriYu** [comment]
I think it is not about "Compilation terminated error". So please post a new issue about the tf errors.

**Comment by MoriKen254** [comment]
I believe the compilation terminated error got fixed so let me close this issue ;-)
