### ISSUE TITLE
tf Error

### ISSUE THREAD

**Issue by MoriKen254** [CIR-KIT-Unit03/cirkit_unit03_apps#19]
About tf error methoned in #18 by @Ayushas2427

I confirmed the same error on my PC with ROS kinetic, whose CPU is core i5.

By the way, I don't think openCV causes the error. We must fix something on tf between `odom` and `map`. Maybe `odom` frame publishing rate is too slow for local planner.

Any ideas and trial results?

**Comment by MoriKen254** [comment]
@Ayushas2427

Finally gotcha in my environment at least! 

## Solution

Try to edit the following code

- https://github.com/CIR-KIT-Unit03/cirkit_unit03_navigation/blob/master/cirkit_unit03_amcl/config/amcl_params_gazebo.yaml#L7

and adjust the parameter larger. I changed it to 4.0 but this should be up to your PC Spec so tune it by yourself.

```
transform_tolerance: 0.2
```

also please delete the following duplicate line to prevent overwriting the param.

- https://github.com/CIR-KIT-Unit03/cirkit_unit03_navigation/blob/master/cirkit_unit03_amcl/config/amcl_params_gazebo.yaml#L33

## Meaning

Have a look at http://wiki.ros.org/amcl#Parameters for the meaning of the param.

```
~transform_tolerance (double, default: 0.1 seconds)
Time with which to post-date the transform that is published, to indicate that this transform is valid into the future.
```

## Detail

In detail, I suppose this param is set to the duration time for `waitForTransform` method in `amcl`  like the following.

```
listener.waitForTransform("/odom","/map",rospy.Time.now(),rospy.Duration(XXX <- HERE))
```

- Related forums
  * http://answers.ros.org/question/190052/transform-tolerance/
  * http://answers.ros.org/question/106261/extrapolation-error-and-amcl/
  * http://answers.ros.org/question/164911/move_base-and-extrapolation-errors-into-the-future/
  * http://answers.ros.org/question/192010/amcl-publish-frequency-map-odom/

The method wait until the newest tf msg comes so as to prevent delay problem discussed in this issue. The default value 0.1 is too short for our normal laptop to process whole apps including heavy rviz and gazebo.

Hope this'll help you.

Take care

**Comment by Ayushas2427** [comment]
Respected @MoriKen254,
Great to have your help in this.
Thank you for such a detailed explanation!

As you mentioned, i completely agree with you that the value basically corresponds to the time allocation.

I am in process of varying the values and shall revert accordingly in a couple of minutes.

NOte:
**This note point is something out of this ques. So, I regret for the inconvenience** 
I am currently working with built-in packages and node files and all. Now, I wish to start as a developer, I want to edit your packages and wish to modify them as per my needs. The main problems lies in the fact that I have no such idea about Python!
Just to be ensured, I want you (as you could help me in the best possible way) to suggest me the source, from where I can learn this super important language Python, so that I can write ad modify my own node files!
I want the quickest way for this, and surely not the easiest!
Thank you!

**Comment by Ayushas2427** [comment]
Ohk, I changed the tolerance limits to 4.0, and then to 8.0 and then some other random value!

Unfortunately, I am getting the following error on my terminal!

![ros_error_7](https://user-images.githubusercontent.com/25845090/27817696-15114874-60b0-11e7-9f11-8c02fed7a577.png)

Btw, I am also using the i5 based pc and I have deleted the redundant line as you have mentioned/

Thanks

**Comment by MoriKen254** [comment]
@Ayushas2427 

If you wanna learn ROS with python, they're gonna be good.

http://wiki.ros.org/Books/ROSbyExample
http://wiki.ros.org/Books/ROSbyExampleVol2

If you wanna learn python from scratch, I'm afraid I cannot recommend a English textbook cuz I learned it in my language Japanese. You can search a bunch of texts on line or web materials.

**Comment by Ayushas2427** [comment]
Sure sir.
I shall follow them.
Though i am now getting new error in my terminal as:

![ros_error_8](https://user-images.githubusercontent.com/25845090/27820182-2a751316-60bb-11e7-97cd-4b0e33ee966f.png)

But I am not sure whether these errors will be solved or not!
Thanks for the help sir.
Regards

**Comment by MoriKen254** [comment]
@Ayushas2427 

It seems tf isn't published properly yet (not only odom and map but also base_link and map). Can you show tf tree with rqt? Also, what your rviz says about TF (on the left hand window in rviz)?

How about setting transform_tolerance to 2? In my environment, 4 was too large so I modified so. However this just caused another problem in my environment so I little expect it.

Make sure to launch autorun file once. btw, which launch file are you using?

**Comment by Ayushas2427** [comment]
Respected @MoriKen254,
Please find the following procedure I am using.

1: 
![ros_check_1](https://user-images.githubusercontent.com/25845090/27827443-f0e43748-60d4-11e7-9fea-d99bb6c156a8.png)

2:This gives me the following output. With the initial error as showsn
![ros_check_2](https://user-images.githubusercontent.com/25845090/27827450-f66ca02e-60d4-11e7-98b9-cbe73257b36a.png)

3: Giving a 2D Nav Goal and the bot starts. After sometimes, the bot starts behaving in a less stable manner, and I get the error as follows:
![ros_check_3](https://user-images.githubusercontent.com/25845090/27827499-2fe13734-60d5-11e7-8251-c04d2f081664.png)

<Note: I have set the transform_tolerance" to 2 in this case.>

![ros_bot_tree_tf](https://user-images.githubusercontent.com/25845090/27827757-7b600612-60d6-11e7-9e3d-cb983735848e.png)

I have been trying for a bit long time, but unfortunately, unable to rectify this so far.

Regards

**Comment by MoriKen254** [comment]
@Ayushas2427 

Thanks for your captures.

## Solution

Try to modify the following line

https://github.com/CIR-KIT-Unit03/cirkit_unit03_apps/blob/master/cirkit_unit03_autorun/launch/gazebo/autorun_gazebo.launch#L22

```
<arg name="time" value="6" />
```

larger than 6 for example 10. it's up to your env.

## Reason

Unfortunately, laser merger node must wait until both of two original lasers are surely published. If the merger runs before the two lasers get available, you'll get the error. In default, we set it's 6 sec but it doesn't seem to match your PC so please adjust it a larger value.

## Pose estimate before nav goal
Moreover, please use 2D pose estimate in Rviz in order to set robot initial pose close to the position in Gazebo before using 2D Nav Goal.

**Comment by Ayushas2427** [comment]
Thank you again for you rhelp.
And I am really feeling very sorry, as you are really trying to rectify my error, but unfortunately, it not working!
It is exactly sam eas before.
I have used 2D pose estimation also, and the value has been tested with '10' and then '15'.

Maybe, I should recompile and whole package and should configure the whole pcl installation and package cloning. I guess you will also agree with this.
Regards

**Comment by MoriKen254** [comment]
@Ayushas2427 

OK!

Only one thing. Before reinstalling whole stuff, plz check the following file out.

https://github.com/CIR-KIT-Unit03/cirkit_unit03_apps/blob/kinetic-devel/cirkit_unit03_autorun/launch/gazebo/autorun_gazebo.launch

This file was modified because I got a similar error with you. The main difference is all the launch files are launched through timed_roslaunch node and delay times are set in a proper order to start up.

At least in my PC, the similar errors disappeared. I believe it's worthwhile trying the launch file.

```xml
<launch>
  <include file="$(find cirkit_unit03_gazebo)/launch/cirkit_unit03_clearpath_playpen.launch"/>

  <node name="map_server" pkg="map_server" type="map_server" args="$(find cirkit_unit03_maps)/map/playpen_map.yaml" />

  <include file="$(find timed_roslaunch)/launch/timed_roslaunch.launch">
    <arg name="time" value="5" />
    <arg name="pkg" value="cirkit_unit03_move_base" />
    <arg name="file" value="move_base_gazebo.launch" />
    <arg name="node_name" value="timed_move_base_gazebo" />
  </include>

  <include file="$(find timed_roslaunch)/launch/timed_roslaunch.launch">
    <arg name="time" value="6" />
    <arg name="pkg" value="cirkit_unit03_amcl" />
    <arg name="file" value="amcl_diff_gazebo.launch" />
    <arg name="node_name" value="timed_amcl_diff_gazebo" />
  </include>

  <!-- laserscan_merger should be executed after all launch files are called --> 
  <include file="$(find timed_roslaunch)/launch/timed_roslaunch.launch">
    <arg name="time" value="10" />
    <arg name="pkg" value="cirkit_unit03_control" />
    <arg name="file" value="laserscan_merger.launch" />
    <arg name="node_name" value="timed_laser_scan_merger" />
  </include>


  <include file="$(find timed_roslaunch)/launch/timed_roslaunch.launch">
    <arg name="time" value="12" />
    <arg name="pkg" value="cirkit_unit03_control" />
    <arg name="file" value="control_gazebo.launch" />
    <arg name="node_name" value="timed_cirkit_unit03_control" />
  </include>

  <node pkg="topic_tools" type="relay" name="relay_base_scan" args="/cirkit_unit03/laser/base_scan /base_scan"/>
  <node pkg="topic_tools" type="relay" name="relay_base_scan2" args="/cirkit_unit03/laser/base_scan2 /base_scan2"/>

  <node name="rviz" pkg="rviz" type="rviz" args="-d $(find cirkit_unit03_autorun)/rviz/gazebo/autorun_gazebo.rviz" required="true" />
</launch>
``` 

Regards

**Comment by Ayushas2427** [comment]
Respected Sir,
A very good morning from India!
Sorry for the late reply. I got stuck with the MATLAB Related tasks.
I tried the modified file, but as you could anticipate, it failed to rectify the error!
I must reinstall each package and file!
Last time, it took me several days to install pcl and I had to made some changes in cmake list files to write "pc" related command files.
Since then, I somehow managed to get this working but with errors!

Re-installation will lead me to all those out of world pcl related installation steps!
But I cannot skip this, as your packages are veryy fine for my task and I must do them in order to implement navigation with car like model!

Now, this one could be absurd, but can I have a couple of minute session with you/any other colleague of yours, with whom I could install and work with your wonderful package so that I could start working on them? This session could be via hangout or skype or so.

I regret if this seems to be a poor request. Also, this will surely cause you some waste of time, but for me,as a student of graduation, it could resolve every bit of problem.
Kindly revert on this, whether You agree for a session or not, so that I could start looking for some other ways of rectifying the error.

My best Regards to you and your team.
Ayush Sharma
ayush.279@gmail.com

**Comment by MoriKen254** [comment]
@Ayushas2427 

I have an idea.

I noticed that our application package was too complicated for beginners. Thanks and sorry for your struggles.

I have came to think that I don't want to bother users including you to install dependent packages. So let me create a simpler and minimal application which doesn't use `pcl` and `lrf_merger`.

I feel sorry that you've been annoyed with handling just "dependent" packages. Moreover, I don't think it's essential to use such packages for your purpose that I just wanna try to "use car-like model".

Please give me a couple of days and want you (and other users in the future) to use our model more easily. I believe this would be more essential solution.

If some very difficult errors occurs after using a next coming package, we'll have a chance to have some chats.

Regards.

**Comment by Ayushas2427** [comment]
Respected @MoriKen254 ,
I thank you for the level of cooperation.
Nothing could be better than what you have just suggested.

I shall wait for the same.
My best Regards

**Comment by MoriKen254** [comment]
@Ayushas2427 

Here you go. Try the following package, which no longer requires pcl and mergers.

https://github.com/CIR-KIT-Unit03/cirkit_unit03_simple_apps

```bash
$ cd <catkin_ws>/src
$ git clone https://github.com/CIR-KIT-Unit03/cirkit_unit03_simple_apps.git
$ cd cirkit_unit03_simple_apps
$ source install.sh
... after building
$ cd <catkin_ws>
$ source devel/setup.bash
$ roslaunch cirkit_unit03_simple_navi simple_navi.launch
```

I tried the simulation with two different PCs of mine, and checked it functioned finely on both PCs. Hope you'll also succeed.

**Comment by Ayushas2427** [comment]
Respected @MoriKen254 ,
The model is now responding in a bit better manner.

In terms of error, the error received is now as follows:
```
[ERROR] [1500888543.353475214, 1346.950000000]: Extrapolation Error: Lookup would require extrapolation into the future.  Requested time 1346.430000000 but the latest data is at time 1345.260000000, when looking up transform from frame [odom] to frame [map]

[ERROR] [1500888543.353571119, 1346.950000000]: Global Frame: odom Plan Frame size 525: map

[ERROR] [1500888543.422232424, 1347.000000000]: Cannot clear map because pose cannot be retrieved
[ERROR] [1500888548.037000134, 1351.600000000]: Cannot clear map because pose cannot be retrieved
```

Please note that my lab's proxy settings are not allowing me to git clone repositories. so I used performed the installation and rest as root. Hope that wont be reason of the error.

Regards

**Comment by Ayushas2427** [comment]
This error is occurring randomly.
Sometimes it works perfectly well and reaches the goal , but whenever it gets stuck with the obstacles, this error occurs.

I have no idea of how and what does this signify.
Thanks

**Comment by MoriKen254** [comment]
In order to avoid tf frame error, try to tune `transform_tolerance` parameter of `amcl` larger if it happens frequently.

https://github.com/CIR-KIT-Unit03/cirkit_unit03_navigation/blob/simple/cirkit_unit03_amcl/config/amcl_params_gazebo.yaml#L7

Next, `move_base` usually throws the error `Cannot clear map because pose cannot be retrieved` occurs when it gets stuck with the obstacles, which means a goal is set at the difficult position to proceed. It is `move_base`'s specification. It can't be helped...

Please try to set a goal that a planed path would not interfere with obstacles. 

I'm really glad that you are trying to use our original packages. However I'm afraid I hope you will firstly try to read basic ROS's `navigation` related documentation and understand the contents more deeply. It seems that you don't understand which error if from ROS general one or our specific package one.

Our packages are somewhat applied so I recommend you use http://wiki.ros.org/Robots/Husky first, which is more basic.

**Comment by Ayushas2427** [comment]
ok.
Thanks for bearing the endless issues from my side.
Thanks for the cooperation.

**You may kindly close this issue.**
Best Regards

**Comment by MoriKen254** [comment]
@Ayushas2427 

It was too strong. It was my fault. I apologize for making you feel unpleasant. I'm not sure if you believe me or not but that was not my intention at all. Sorry about that.

Please let me throw some suggestions on the issue here because I hope it can help you.

According to the point `Sometimes it works perfectly well and reaches the goal`, car-like steering controller itself works finely I guess. Essential problem here is just to follow ROS's general move_base's specification.

- reference
  * http://wiki.ros.org/move_base
  * http://wiki.ros.org/navigation/Tutorials

Please try the following if you are patient to avoid `move_base` planning error. 

- set a goal to a close point from the current robot position.
- avoid a goal requiring sharp pose change (needs sharp curving operation signal) especially if a robot is surrounded by obstacles.
- If you want to lead a robot to a far point, set a goal one by one in a little by little distance to attract a robot to the goal gradually.

`move_base` node in ROS's navigation stack is kinda sensitive on planning so we have to be very careful on setting a goal.

If you feel using operation from navigation stuff is uncomfortable, you can try to use `teleop_twist_node`, which enables you to send velocity command from joy pad like a PlayStation's controller.

- reference
  * http://wiki.ros.org/teleop_twist_joy

operation from keyboard is also available.

- reference
  * http://wiki.ros.org/teleop_twist_keyboard

Please try to search further detailed information on how to use these nodes.

Best Regards

**Comment by Ayushas2427** [comment]
Respected @MoriKen254 ,
You must not apologize. I completely understand your point and you are absolutely correct about my current level of knowledge.

Before proceeding with the error rectification, I must go through all the documentations.
I need to understand how your packages are working.
Most importantly, I liked this package as this is one of the very few open source data on how one can implement "amcl" and navigation with four wheeled models.
I must understand first how the model is being localised. What all sensor data it is using to be localised in a given environment (especially outdoor scenarios). If the system is using Lidar sort of, then does that mean that the model is capable of understanding it's position in indoor situations only?
**I must understand the AMCL working first.**
After I get this level of understanding, then only I will proceed with the error.

My current expertise is causing a bit of difficulty in understanding the stuff. Instead of acting as a fool by simply testing without any prior knowledge, I must understand things fisrt else, I won't be getting any fruitful results.

I thank you for the immense help and endless level of cooperation from your side.

My best regards to you and your team
Ayush Sharma
