### ISSUE TITLE
UBUNTU 16 and ROS KINECT

### ISSUE THREAD

**Issue by sarthakprakash** [CIR-KIT-Unit03/cirkit_unit03_apps#20]
How can I make this package work in Ubuntu 16 and  Kinect

**Comment by MoriKen254** [comment]
Try the following commands.

```bash
(in your workspace)
$ git clone -b kinetic-devel https://github.com/CIR-KIT-Unit03/cirkit_unit03_apps
$ cd cirkit_unit03_apps
$ sh install.sh
```

The script resolves all dependencies properly. Then please launch the following autorun file after catkin_make.

```bash
$ roslaunch cirkit_unit03_autorun autorun_gazebo.launch
```

[![steer_drive_controller_kinetic_demo](https://i.ytimg.com/vi/O2TjvZomuYY/hqdefault.jpg)](https://youtu.be/O2TjvZomuYY)
